name: hlep
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/jabee.png
  - assets/googlemaps.png
  - assets/jollibee/jolli_ricemeal.jpg
  - assets/jollibee/jolli_ricemeal1.jpg
  - assets/jollibee/jolli_snacks.jpg
  - assets/jollibee/jolli_snacks1.jpg
  - assets/jollibee/jolli_groupmeals.jpg
  - assets/jollibee/jolli_groupmeals1.jpg
  - assets/jollibee/jolli_desserts.jpg
  - assets/jollibee/jolli_desserts1.jpg
  - assets/chowking/chow_snacks.jpg
  - assets/chowking/chow_snacks1.jpg
  - assets/chowking/chow_ricemeal.jpg
  - assets/chowking/chow_ricemeal1.jpg
  - assets/chowking/chow_groupmeals.jpg
  - assets/chowking/chow_groupmeals1.jpg
  - assets/chowking/chow_desserts.jpg
  - assets/chowking/chow_desserts1.jpg
  - assets/greenwich/green_snacks.jpg
  - assets/greenwich/green_snacks1.jpg
  - assets/greenwich/green_pizza.jpg
  - assets/greenwich/green_pizza1.jpg
  - assets/greenwich/green_pizza2.jpg
  - assets/greenwich/green_pizza3.jpg
  - assets/manginasal/mang_snacks.jpg
  - assets/manginasal/mang_ricemeals.jpg
  - assets/manginasal/mang_ricemeals1.jpg
  - assets/manginasal/mang_group.jpg
  - assets/manginasal/mang_group1.jpg
  - assets/manginasal/mang_dessert.jpg
  - assets/manginasal/mang_dessert1.jpg
  - assets/bev/bev_soft.jpg
  - assets/bev/bev_soft1.jpg
  - assets/bev/bev_soft2.jpg
  - assets/bev/bev_soft3.jpg
  - assets/bev/bev_soft4.jpg
  - assets/qrs/qr1.png
  - assets/qrs/qr2.png
  - assets/qrs/qr3.png
  - assets/qrs/qr4.png
  - assets/qrs/qr5.png
  - assets/qrs/qr6.png
  - assets/gcash_logo.png
  - assets/maya_logo.png
  - assets/combos/comboA.jpg
  - assets/combos/comboB.jpg
  - assets/combos/comboC.jpg
  - assets/combos/comboD.jpg
  - assets/bgwallpaper.png
  - assets/login_wallpaper.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
